# Pull base image.
FROM python:3.5-alpine


RUN git clone https://github.com/benhoyle/website.git

WORKDIR /website

RUN pip install -r requirements.txt

RUN pip install --editable .

VOLUME ./instance/db/:./instance/db/

CMD gunicorn \
    -b :8000 \
    --access-logfile - \
    --reload \
    "benhoyle.app:create_app()" \

